version: '3'
services:
  front:
    container_name: react
    image: wldusdl34/myblogfront:latest
    build: 
      context: ./myblog_front
      dockerfile: ./Dockerfile
    restart: always
    ports:
    - "8080:8080"
