version: '3'
  services:
    front:
      container_name: react
      image: wldusdl34/myblogfront:latest
      build:
        context: .
        dockerfile: ./myblog_front/Dockerfile
      restart: always
      ports:
      - "8080:8080"