version: '3'
services:
  front:
    container_name: react
    image: wldusdl34/myblogfront:latest
    restart: always
    ports:
    - "8080"
    volumes: 
      external: true
    
  back:
    container_name: server
    image: wldusdl34/myblogserver:latest
    restart: always
    ports:
      - "9090"
    volumes: 
      external: true

  nginx:
    container_name: nginx
    build:
      context: ./myblog_nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    volumes: 
      external: true