version: '3'
services:
  front:
    container_name: react
    image: wldusdl34/myblogfront:latest
    restart: always
    ports:
      - mode: host
        protocol: tcp
        published: 8080
        target: 80
    
  back:
    container_name: server
    image: wldusdl34/myblogserver:latest
    restart: always
    ports:
      - mode: host
        protocol: tcp
        published: 9090
        target: 80

  nginx:
    container_name: nginx
    image: wldusdl34/myblognginx:latest
    restart: always
    ports:
      - "80:80"