version: '3'
services:
  front:
    container_name: react
    image: wldusdl34/myblogfront:latest
    restart: always
    ports:
      - "8080"
    
  back:
    container_name: server
    image: wldusdl34/myblogserver:latest
    restart: always
    ports:
      - "9090"

  nginx:
    container_name: nginx
    build:
      context: ./myblog_nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"

  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    ports:
      - "3306"
    volumes:
      - /home/opc/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Dnflwlq@34
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci