version: '3'
services:
  nginx:
    container_name: nginx
    image: wldusdl34/myblognginx:latest
    build: .
    restart: always
    ports:
      - "80:80"

  front:
    container_name: react
    image: wldusdl34/myblogfront:latest
    build: .
    restart: always
    ports:
    - "8080:8080"

  back:
    container_name: server
    image: wldusdl34/myblogserver:latest
    build: .
    restart: always
    ports:
      - "9090:9090"